Tons of updates. Mostly args parsing and debug levels.

diff --git a/morph b/morph
--- a/morph
+++ b/morph
@@ -1,6 +1,16 @@
 #!/bin/sh
 
-MORPH_DIR=$(pwd)
+if ! [ $MORPH_DIR ]; then
+    if [ -d /usr/share/morph ]; then
+        MORPH_DIR=/usr/share/morph
+    else
+        MORPH_DIR=$(dirname $(readlink -f $0))
+    fi
+fi
+
+if [ -z $MORPH_DEBUG ]; then
+    MORPH_DEBUG=0
+fi
 
 . $MORPH_DIR/morphrc
 . $MORPH_DIR/lib/debug
@@ -34,8 +44,9 @@ validate () {
         depends=auto
     fi
 
-
-    target_arch="$(uname -m)"
+    if [ -z $target_arch ]; then
+        target_arch="$(uname -m)"
+    fi
 
     if [ "$arch" == "any" ]; then
         arch=$target_arch
@@ -103,7 +114,7 @@ process_source () {
         for unpacker in $(find $MORPH_DIR/unpackers -type f); do
             . $unpacker
             if can_unpack; then
-                warn "Using unpacker $unpacker"
+                debug "Using unpacker $unpacker"
                 unpack
                 unpacked=1
                 break
@@ -117,7 +128,7 @@ process_source () {
 }
 
 is_function () {
-    type $1 | grep -q 'shell function' &> /dev/null
+    type $1 2>&1 | grep -q 'shell function' &> /dev/null
 }
 
 do_autobuild () {
@@ -126,7 +137,7 @@ do_autobuild () {
     fi
     . $MORPH_DIR/builders/$1
     if can_build; then
-        warn "Using builder $1"
+        debug "Using builder $1"
         build || false
     else
         false
@@ -139,7 +150,7 @@ autobuild () {
     else
         for builder in $(find $MORPH_DIR/builders -type f); do
             if do_autobuild $(basename $builder); then
-                warn "Built using $builder"
+                debug "Built using $builder"
                 built=1
                 break
             fi
@@ -158,7 +169,93 @@ go_src_dir () {
     fi
 }
 
-. ./MORPHBUILD
+# Options:
+# -t, --tree       -- use a build tree
+# -i, --install    -- install package after building
+# -h, --help       -- show help message
+# -s, --spawn      -- spawn a new MORPHLING here
+# --version        -- set version
+# --build          -- set build
+# --target-arch    -- set target arch (for cross)
+
+# Options parsing black magic
+argv=$(getopt -s bash --options "t:ihs" --longoptions tree:,install,help,spawn,version:,build:,target-arch: -n Morph -- $@)
+eval set -- "$argv"
+
+declare -i positional_count=0
+positional_args=""
+
+while [ $1 ]; do
+    if [ $positionals ]; then
+        positional_count=$(($positional_count + 1))
+        positional_args="$1"
+    else
+        case $1 in
+            -t|--tree)
+                shift
+                build_tree=$(dirname $1)/$(basename $1)
+                ;;
+            -i|--install)
+                will_install=1
+                ;;
+            -h|--help)
+                show_help
+                ;;
+            -s|--spawn)
+                if [ -f MORPHLING ]; then
+                    die "There is a MORPHLING here already!"
+                fi
+                cp $MORPH_DIR/SAMPLE MORPHLING
+                exit 0
+                ;;
+            --version)
+                shift
+                # TODO bump magic
+                ;;
+            --build)
+                shift
+                # TODO bump magic
+                ;;
+            --target-arch)
+                shift
+                target_arch=$1
+                ;;
+            --)
+                positionals=1
+                ;;
+        esac
+    fi
+    shift
+done
+
+if [ $build_tree ]; then
+    if [ $positional_count -gt 0 ]; then
+        die "Can't have --tree and positional args at the same time"
+    else
+        tree_path=$(mktemp -d /tmp/morph-tree.XXXXXX)
+        cd $tree_path
+        tar xf $build_tree
+        path=$(pwd)
+    fi
+else
+    if [ "$positional_count" -gt 1 ]; then
+        die "Too many positional arguments!"
+    elif [ "$positional_count" == "1" ]; then
+        if [ -d $positional_args ]; then
+            path=$positional_args
+        else
+            die "$positional_args is not a directory!"
+        fi
+    else
+        path=$(pwd)
+    fi
+fi
+
+if ! [ -f $path/MORPHLING ]; then
+    die "No MORPHLING found in $path!"
+fi
+
+. $path/MORPHLING
 validate
 
 init_structure
